Repository argoapp-live/argo-api, pull requests merged in 2021-07, with the labels that each got.

#59 Dev v2 skynet
  src/components/Configuration/model.ts
  src/components/Deployment/dto-interfaces.ts
  src/components/Deployment/index.ts
  src/components/Organization/index.ts
  src/config/env/index.ts
Labels: enhancement

#86 CircleCI configuration
  .circleci/config.yml
Labels: devops, enhancement

#87 Update CirleCI configuration
  .circleci/config.yml
Labels: enhancement

#88 Add PEM content env var
  env.example
  src/components/GitHubApp/service.ts
  src/config/env/index.ts
  src/routes/AuthRouter.ts
Labels: enhancement

#93 Base64 encode PEM content
  env.example
  src/components/GitHubApp/service.ts
  src/config/env/index.ts
  src/routes/AuthRouter.ts
Labels: devops, enhancement

#94 CircleCI tests enabled
  .circleci/config.yml
  test/api.js
  test/authentication.js
  test/encoding.test.js
  test/fixtures/.gitkeep
  test/fixtures/user.json
  test/index.js
Labels: devops
